#!/usr/bin/env bash
set -e
cd -- "$(dirname -- "$(readlink -f -- "$0")")"
if [[ -x /usr/bin/python3 ]]; then
  exec /usr/bin/python3 -m pulsar3.gui "$@"
else
  exec /usr/bin/python -m pulsar3.gui "$@"
fi
